[toolchain]
anchor_version = "1.0.2"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
transfer_hook_vault = "w7jecRTVoH3FkVSDxuNHJN1PTFi83GieT138r1V3es7"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
